Repository arbor-sim/arbor, pull requests merged in 2019-08, with the labels that each got.

#821 Removed the use of CUDA Managed Memory from GPU-Stack
  arbor/backends/gpu/stack.hpp
  arbor/backends/gpu/threshold_watcher.hpp
  test/unit/test_gpu_stack.cu
Labels: enhancement, optimization

#826 Python wrapper: complete schedule by adding events(t0,t1)
  doc/py_recipe.rst
  python/schedule.cpp
  python/schedule.hpp
  python/test/unit/test_schedules.py
Labels: documentation, python

#827 Python wrapper: add hint_map to domain decomposition
  arbor/partition_load_balance.cpp
  doc/py_domdec.rst
  doc/py_hardware.rst
  python/config.cpp
  python/domain_decomposition.cpp
  python/example/ring.py
  python/test/unit/runner.py
  python/test/unit/test_domain_decompositions.py
  python/test/unit_distributed/runner.py
  python/test/unit_distributed/test_contexts_mpi4py.py
  python/test/unit_distributed/test_domain_decompositions.py
Labels: documentation, python

#834 Replace morphology code with new sample-based morphology parsing.
  CMakeLists.txt
  arbor/CMakeLists.txt
  arbor/cable_cell.cpp
  arbor/include/arbor/cable_cell.hpp
  arbor/include/arbor/morph/error.hpp
  arbor/include/arbor/morph/morphology.hpp
  arbor/include/arbor/morph/primitives.hpp
  arbor/include/arbor/morph/sample_tree.hpp
  arbor/include/arbor/morphology.hpp
  arbor/include/arbor/segment.hpp
  arbor/include/arbor/swcio.hpp
  arbor/morph/morphology.cpp
  arbor/morph/primitives.cpp
  arbor/morph/sample_tree.cpp
  arbor/morphology.cpp
  arbor/swcio.cpp
  arbor/util/range.hpp
  example/single/single.cpp
  lmorpho/CMakeLists.txt
  lmorpho/README.md
  lmorpho/lmorpho.cpp
  lmorpho/lsys_models.cpp
  lmorpho/lsys_models.hpp
  lmorpho/lsystem.cpp
  lmorpho/lsystem.hpp
  lmorpho/morphio.cpp
  lmorpho/morphio.hpp
  test/unit/CMakeLists.txt
  test/unit/test_counter.cpp
  test/unit/test_morphology.cpp
  test/unit/test_range.cpp
  test/unit/test_swcio.cpp
Labels: enhancement

#843 Fix parameter setting in ring example
  example/ring/ring.cpp
Labels: bug
