Repository arbor-sim/arbor, pull requests merged in 2020-04, with the labels that each got.

#1002 Finalize support for PyPi package
  .gitignore
  MANIFEST.in
  setup.py
Labels: python

#1009 Fix bad param values in partial CV coverage.
  arbor/fvm_layout.cpp
  test/unit/test_fvm_layout.cpp
Labels: bug

#1010 Fix setuptools to work with older Pip
  setup.py
Labels: packaging, python
