Repository arbor-sim/arbor, pull requests merged in 2020-10, with the labels that each got.

#1170 Tighten SWC requirements, comments.
  arbor/include/arbor/swcio.hpp
  arbor/swcio.cpp
  test/unit/test_swcio.cpp
Labels: 0.4

#1171 Fix bug setting ext ion concentration
  python/cells.cpp
Labels: 0.4, bug, python

#1167 Docs restructure for 0.4
  doc/ai_library.rst
  doc/ai_nmodl.rst
  doc/ai_sampling_api.rst
  doc/ai_simd_api.rst
  doc/co_cable_cell.rst
  doc/co_cell.rst
  doc/co_domdec.rst
  doc/co_hardware.rst
  doc/co_interconnectivity.rst
  doc/co_labels.rst
  doc/co_mechanisms.rst
  doc/co_morphology.rst
  doc/co_overview.rst
  doc/co_recipe.rst
  doc/co_simulation.rst
  doc/conf.py
  doc/cpp_cable_cell.rst
  doc/cpp_cell.rst
  doc/cpp_distributed_context.rst
  doc/cpp_domdec.rst
  doc/cpp_dry_run.rst
  doc/cpp_hardware.rst
  doc/cpp_interconnectivity.rst
  doc/cpp_overview.rst
  doc/cpp_profiler.rst
  doc/cpp_recipe.rst
  doc/cpp_simulation.rst
  doc/gs_other_examples.rst
  doc/gs_single_cell.rst
  doc/images/arbor-lines-proto-colour-notext.svg
  doc/images/arbor-lines-proto-colour.svg
  doc/images/arbor-logo.svg
  doc/images/single_cell_model_result.svg
  doc/in_build_install.rst
  doc/in_install.rst
  doc/in_python.rst
  doc/in_spack.rst
  doc/index.rst
  doc/library.rst
  doc/mechanisms.rst
  doc/py_cable_cell.rst
  doc/py_cell.rst
  doc/py_common.rst
  doc/py_domdec.rst
  doc/py_hardware.rst
  doc/py_interconnectivity.rst
  doc/py_labels.rst
  doc/py_mechanisms.rst
  doc/py_morphology.rst
  doc/py_overview.rst
  doc/py_profiler.rst
  doc/py_recipe.rst
  doc/py_reference.rst
  doc/requirements.txt
  doc/scripts/make_images.py
  doc/single_cell.rst
Labels: 0.4, documentation

#1166 Update Python examples
  python/example/network_ring.py
  python/example/single_cell_model.py
  python/example/single_cell_multi_branch.py
  python/example/single_cell_swc.py
  python/tutorial/example1.py
Labels: 0.4, python

#1175 Fix some typos
  doc/ai_sampling_api.rst
  doc/co_cell.rst
  doc/py_domdec.rst
  doc/py_morphology.rst
  doc/py_simulation.rst
Labels: 0.4

#1174 Fixes the curious case of the missing quotes in the Python single cell model example, both code and docs.
  doc/gs_single_cell.rst
  python/example/single_cell_model.py
Labels: 0.4

#1177 Fixes imports that are no longer required and causes RTD to fail building
  doc/gs_single_cell.rst
  doc/scripts/make_images.py
Labels: 0.4

#1185 Remove Python API ref page, Spack Install, fix some links
  doc/conf.py
  doc/cpp_recipe.rst
  doc/gs_single_cell.rst
  doc/in_install.rst
  doc/in_python.rst
  doc/index.rst
  doc/py_overview.rst
  doc/py_recipe.rst
  doc/py_reference.rst
Labels: 0.4, documentation

#1184 Docs: minor plot tweaking
  doc/gs_single_cell.rst
  doc/images/single_cell_model_result.svg
  python/example/single_cell_model.py
Labels: 0.4, documentation

#1183 Add python examples to CI
  .travis.yml
  python/example/network_ring.py
  python/example/single_cell_model.py
  python/example/single_cell_multi_branch.py
  python/example/single_cell_swc.py
  scripts/travis/build.sh
Labels: 0.4, CI/CD

#1188 Rearranged the documentation source to have nicer URLs on the website.
  .readthedocs.yml
  doc/concepts/cable_cell.rst
  doc/concepts/cell.rst
  doc/concepts/domdec.rst
  doc/concepts/hardware.rst
  doc/concepts/index.rst
  doc/concepts/interconnectivity.rst
  doc/concepts/labels.rst
  doc/concepts/mechanisms.rst
  doc/concepts/morphology.rst
  doc/concepts/recipe.rst
  doc/concepts/simulation.rst
  doc/cpp/cable_cell.rst
  doc/cpp/cell.rst
  doc/cpp/domdec.rst
  doc/cpp/hardware.rst
  doc/cpp/index.rst
  doc/cpp/interconnectivity.rst
  doc/cpp/neuroml.rst
  doc/cpp/profiler.rst
  doc/cpp/recipe.rst
  doc/cpp/simulation.rst
  doc/hpc/distributed_context.rst
  doc/hpc/dry_run.rst
  doc/hpc/index.rst
  doc/index.rst
  doc/install/build_install.rst
  doc/install/index.rst
  doc/install/python.rst
  doc/install/spack.rst
  doc/internals/index.rst
  doc/internals/nmodl.rst
  doc/internals/sampling_api.rst
  doc/internals/simd_api.rst
  doc/internals/util.rst
  doc/python/cable_cell.rst
  doc/python/cell.rst
  doc/python/domdec.rst
  doc/python/hardware.rst
  doc/python/index.rst
  doc/python/interconnectivity.rst
  doc/python/labels.rst
  doc/python/mechanisms.rst
  doc/python/morphology.rst
  doc/python/profiler.rst
  doc/python/recipe.rst
  doc/python/simulation.rst
  doc/requirements.txt
  doc/tutorial/index.rst
  doc/tutorial/single_cell_model.rst
  doc/tutorial/single_cell_model_result.svg
Labels: 0.4, documentation

#1191 update config and version for v0.4
  VERSION
  setup.py
Labels: 0.4
