Repository arbor-sim/arbor, pull requests merged in 2021-01, with the labels that each got.

#1293 Remove dependence of docs on the Python module
  .github/workflows/basic.yml
  CMakeLists.txt
  doc/conf.py
  doc/install/build_install.rst
  doc/install/python.rst
  doc/scripts/inputs.py
  python/CMakeLists.txt
  setup.py
Labels: broke the build, python

#1296 Add numpy to requirements
  setup.py
Labels: bug

#1302 Docs: define branch, mlocation, cv default.
  doc/concepts/cable_cell.rst
  doc/concepts/cell.rst
  doc/concepts/labels.rst
  doc/concepts/morphology.rst
  doc/concepts/simulation.rst
  doc/cpp/index.rst
  doc/cpp/simulation.rst
  doc/python/labels.rst
  doc/python/mechanisms.rst
  doc/scripts/inputs.py
  doc/scripts/make_images.py
  doc/tutorial/single_cell_model.rst
  python/example/single_cell_model.py
  python/example/single_cell_recipe.py
Labels: documentation
