Repository arbor-sim/arbor, pull requests merged in 2021-02, with the labels that each got.

#1331 Clarify sample collection in distributed contexts.
  doc/python/simulation.rst
Labels: documentation

#1287 Allow dynamically creating and loading of mechanism catalogue
  CMakeLists.txt
  arbor/arbexcept.cpp
  arbor/include/arbor/arbexcept.hpp
  arbor/include/arbor/mechcat.hpp
  arbor/mechcat.cpp
  cmake/CompilerOptions.cmake
  cmake/arbor-config.cmake.in
  doc/concepts/mechanisms.rst
  doc/internals/extending-catalogues.rst
  mechanisms/BuildModules.cmake
  mechanisms/CMakeLists.txt
  mechanisms/generate_catalogue
  python/example/cat/dummy.mod
  python/example/dynamic-catalogue.py
  python/mechanism.cpp
  python/test/unit/runner.py
  python/test/unit/test_catalogues.py
  scripts/build-catalogue
  test/unit/CMakeLists.txt
  test/unit/dummy/dummy.mod
  test/unit/test_mechcat.cpp
Labels: enhancement, interface, nmodl

#1355 remove all mention of travis, update badges
  .travis.yml
  README.md
  doc/contrib/pr.rst
  doc/index.rst
  scripts/travis/build.sh
Labels: CI/CD, documentation

#1360 Modcc: comments & seg fault
  modcc/lexer.cpp
  modcc/module.cpp
  test/unit-modcc/test_lexer.cpp
Labels: bug
